<!-- Root element of PhotoSwipe. Must have class pswp. -->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

        <!-- Background of PhotoSwipe. 
             It's a separate element as animating opacity is faster than rgba(). -->
        <div class="pswp__bg"></div>

        <!-- Slides wrapper with overflow:hidden. -->
        <div class="pswp__scroll-wrap">

            <!-- Container that holds slides. 
                PhotoSwipe keeps only 3 of them in the DOM to save memory.
                Don't modify these 3 pswp__item elements, data is added later on. -->
            
                
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <!-- Aqui la imagen -->
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>
          
            <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
            <div class="pswp__ui pswp__ui--hidden">

                <div class="pswp__top-bar">

                    <!--  Controls are self-explanatory. Order can be changed. -->

                    <div class="pswp__counter"></div>

                   <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

               <!--   <button class="pswp__button pswp__button--share" title="Share"></button> -->

               <!-- <button class="pswp__button pswp__button- -fs" title="Toggle fullscreen"></button>  -->

                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                    <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                    <!-- element will get class pswp__preloader- -active when preloader is running -->
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                          <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                          </div>
                        </div>
                    </div>
                </div>

                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div> 
                </div>
                <div class="controles_galeria">
                  
                </div>
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>

            </div>

        </div>

    </div>

<script >

        var openPhotoSwipe = function(i) {


            var pswpElement = document.querySelectorAll('.pswp')[0];

            // build items array
            var items = [];
                <?php 
                $x = 0;
                if(!empty($lista_admin_data))
                {
                    foreach ($lista_admin_data as $k => $v)
                    {
                        
                       if(file_exists(PROJECT_DIR.$MyConfigure->getUploadDir()."/galeria/".$v["id_album"]."/".$v["foto"])){ 
                       list($ancho, $alto, $tipo, $atributos) = getimagesize(PROJECT_DIR.$MyConfigure->getUploadDir()."/galeria/".$v["id_album"]."/".$v["foto"]); 
                    ?>
                   
                       items.push(  
                        {  
                        src: '<?php echo $MyRequest->getPROTOCOLO().$MyRequest->getSERVER().($_SERVER['SERVER_PORT'] != 80 ? ':'.$_SERVER['SERVER_PORT'] : '').$MyConfigure->getUploadDir()."/galeria/".$v["id_album"]."/".$v["foto"]; ?>',
                        w: "<?php echo $ancho; ?>",
                        h: "<?php echo $alto; ?>",
                        title: JSON.stringify("<?php echo utf8_decode($v["descripcion"]); ?>"),
                        pid: '<?php echo $x; ?>'
                    });
                    <?php $x++; ?>
                       <?php } ?>
                <?php }; ?>
            <?php } ?>

                          
            var options = {
                     // history & focus options are disabled on CodePen        
                history: true,
                focus: false,
                index: parseInt(i),
                galleryUID: 1,
                 galleryPIDs:true,
                showAnimationDuration: 0,
                hideAnimationDuration: 0,
                closeOnScroll: false,
               

                getNumItemsFn: function(){
                    if(items.length == 1)
                    {
                        $(".controles_galeria").html('');
                    }
                    else
                    {
                        $(".controles_galeria").html(
                                '<button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></'+'button>\
                                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></'+'button>');
                    }
                    return items.length;
                }
            };

            var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
            gallery.init();

        };


        $(document).ready(function(){
            $("a[rel=galeria]").click(function(e){

                e.preventDefault();

                var a =  $(this).attr("href").split('#') ;
                var pid = a[1].match(/pid=(\d+)/);
                if(pid.length > 0)
                {
                   openPhotoSwipe(pid[1]);
                }
            });

            var a = (window.location.href.split('#')) ;
            if(a[1])
            {
                var pid = a[1].match(/pid=(\d+)/);

                if(pid.length > 0)
                {
                    openPhotoSwipe(pid[1]);
                }
            }

        });              
</script>